### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by ttarczynski** [sensu-plugins/sensu-plugins-cpu-checks#14]
The latest gem I can find is 0.0.4 which has a fixed version dependency to `sensu-plugin`:

```
sensu-plugin (= 1.2.0)
```

And this results in the following error after updating sensu to version 0.25.0:

```
# /opt/sensu/embedded/bin/check-cpu.rb --help
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'sensu-plugin' (= 1.2.0) - did find: [sensu-plugin-1.3.0] (Gem::MissingSpecVersionError)
```

It's already fixed on master:
[sensu-plugins-cpu-checks.gemspec#L41](https://github.com/sensu-plugins/sensu-plugins-cpu-checks/blob/master/sensu-plugins-cpu-checks.gemspec#L41)

```
s.add_runtime_dependency 'sensu-plugin', '~> 1.2'
```

**Comment by eheydrick** [comment]
1.0.0 was released with the updated `sensu-plugin` dependency spec.
