### ISSUE TITLE
gem installation fails on windows due to  linux-kstat 0.1.3 dependency

### ISSUE THREAD

**Issue by troglas** [sensu-plugins/sensu-plugins-cpu-checks#34]
Hi,
having installed sensu 1.4.2-4  on windows, the command
C:\opt\sensu\embedded\bin\gem install sensu-plugins-cpu-checks fails with error:

ERROR:  Could not find a valid gem 'linux-kstat' (= 0.1.3) in any repository
ERROR:  Possible alternatives: linux-kstat

When I try to download linux-kstat I see only 0.1.0 using gem install linux-kstat I see only 0.1.0 version available.

Best regards,

**Comment by majormoses** [comment]
I believe this is the same issue as #28 closing as a duplicate and will update that issue title so its easier for people to find.
